encoding: utf-8
highlighter: pygments

exclude: ["alexanderzobnin.github.io.sublime-project",
          "alexanderzobnin.github.io.sublime-workspace",
          "jekyll_serve.bat",
          "README.md"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"